
development:
  adapter: mysql2
  database: test 
  host: localhost 
  username: root 
  password: 

test:
  adapter: mysql2
  database: test 
  host: localhost 
  username: root 
  password: 

production:
  adapter: mysql2
  database: lehazi_com 
  host: localhost 
  username: root 
  password: 17qupiaoLIU
