
development:
  adapter: mysql2
  database: development
  host: localhost 
  username: lehazi 
  password: lehazibu
  pool: 5
  timeout: 5000
  encoding: utf8
  
test:
  adapter: mysql2
  database: test 
  host: localhost 
  username: lehazi 
  password: lehazibu
  pool: 5
  timeout: 5000
  encoding: utf8

production:
  adapter: mysql2
  database: lehazi_com 
  host: localhost 
  username: lehazi 
  password: lehazibu
  pool: 5
  timeout: 5000
  encoding: utf8